var teaLine =[ 'naeem','monir', 'dulu', 'noman', 'abir'];
teaLine.push('masum');
console.log(teaLine);
teaLine.pop();
console.log(teaLine);
teaLine.shift();
console.log(teaLine);
teaLine.unshift("naeem");
console.log(teaLine);
var part=teaLine.slice(2,4);
console.log(part);